belanja1=(input("Masukkan daftar belanja 1: "))
belanja2=(input("Masukkan daftar belanja 2: "))
tambahanbelanja1=(input("Tambahkan data ke daftar belanja 1: "))
tambahanbelanja2=(input("Tambahkan data ke daftar belanja 2: "))
print("Daftar belanja 1 adalah %s,%s"%(belanja1,tambahanbelanja1))
print("Daftar belanja 2 adalah %s,%s"%(belanja2,tambahanbelanja2))
