belanja1=(input("Masukkan daftar belanja 1: "))
belanja2=(input("Masukkan daftar belanja 2: "))
tambahbelanja1=(input("Tambahkan data ke daftar belanja 1: "))
tambahbelanja2=(input("Tambahkan data ke daftar belanja 2: "))
print("Daftar belanja 1 adalah %s,%s"%(belanja1,tambahbelanja1))
print("Daftar belanja 2 adalah %s,%s"%(belanja2,tambahbelanja2))
